acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.userlogin, name="login"),
    path('signup/', views.signup, name="signup"),
    path('logout/', views.userlogout, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update")
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include("acc.urls")),
    path('board/', include("board.urls")),
    path('vote/', include("vote.urls")),
    path('trans/', include("trans.urls")),
    path('book/', include("book.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vote/urls.py
from django.urls import path
from . import views

app_name = "vote"
urlpatterns = [
    path('index/' , views.index, name="index"),
    path('detail/<tpk>', views.detail, name="detail"),
    path('vote/<tpk>', views.vote, name="vote"),
    path('cancel/<tpk>', views.cancel, name="cancel"),
    path('create/', views.create, name="create"),
    path('delete/<tpk>', views.delete, name="delete")
]

vote/models.py
from django.db import models
from acc.models import User

# Create your models here.
class Topic(models.Model):
    subject = models.CharField(max_length=100)
    maker = models.ForeignKey(User, on_delete=models.CASCADE, related_name="maker")
    content = models.TextField()
    voter = models.ManyToManyField(User, blank=True, related_name="voter")
    pubdate = models.DateTimeField()

    def __str__(self):
        return self.subject

    def summary(self):
        if len(self.content) > 15:
            return f"{self.content[:15]} ..."
        return self.content
    

class Choice(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    pic = models.ImageField(upload_to="vote/%y")
    con = models.TextField()
    choicer = models.ManyToManyField(User, blank=True)

    def __str__(self):
        return f"{self.topic}__{self.name}"

vote/views.py
from django.shortcuts import render, redirect
from .models import Topic, Choice
from django.utils import timezone
# Create your views here.

def delete(request, tpk):
    t = Topic.objects.get(id=tpk)
    if t.maker == request.user:
        cset = t.choice_set.all()
        for i in cset:
            i.pic.delete()
        t.delete()
    else:
        pass # 메세지
    return redirect("vote:index")


def create(request):
    if request.method == "POST":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        cn = request.POST.getlist("cname")
        cs = request.POST.getlist("ccon")
        cp = request.FILES.getlist("cpic")
        
        # 토픽생성
        t = Topic(subject=s, maker=request.user, content=c, pubdate=timezone.now())
        t.save()
        for na, co, pi in zip(cn,cs,cp):
            Choice(topic=t, name=na, con=co, pic=pi).save()
        return redirect("vote:index")

    return render(request, "vote/create.html")

def cancel(request, tpk):
    u = request.user
    t = Topic.objects.get(id=tpk)
    if u in t.voter.all():
        t.voter.remove(u)
        u.choice_set.get(topic=t).choicer.remove(u)
    return redirect("vote:detail", tpk)


def vote(request, tpk):
    t = Topic.objects.get(id=tpk)
    if not request.user in t.voter.all():
        t.voter.add(request.user)
        cpk = request.POST.get("cho")
        c = Choice.objects.get(id=cpk)
        c.choicer.add(request.user)
    return redirect("vote:detail", tpk)


def detail(request, tpk):
    t = Topic.objects.get(id=tpk)
    c = t.choice_set.all()
    context = {
        "t" : t,
        "cset" : c,
    }
    return render(request, "vote/detail.html", context)

def index(request):
    t = Topic.objects.all()
    t = t.order_by("-pubdate")
    context = {
        "tset" : t
    }
    return render(request, "vote/index.html", context)


    

templates/vote/create.html
{% extends 'base.html' %}
{% block con %}

  
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container mt-5 mb-5">
            <h1><b>토픽생성</b></h1>

            <input type="text" name="sub" class="form-control mt-5" placeholder="TOPIC 제목을 입력하세요">
            <textarea name="con" class="form-control mt-4" placeholder="TOPIC 에 관해서 간단하게 설명해주세요" style="height: 150px;"></textarea>

            <div class="text-end mt-4">
                <button class="btn btn-secondary" type="button" onclick="makesel()">보기생성</button>
                <button class="btn btn-dark">토픽생성</button>
            </div>

            <div id="here" class="row mt-5">
            </div>
        </div>
    </form>
    


    <script>
        function makesel(){
            d = document.getElementById("here");
            n = document.createElement("div");
            n.setAttribute("class", "col-lg-4 mt-5");
            n.innerHTML = '<input type="text" name="cname" class="form-control" placeholder="보기이름입력">\
                <input type="file" name="cpic" class="form-control mt-3 mb-3">\
                <textarea placeholder="보기설명" name="ccon" class="form-control"></textarea>';
            d.appendChild(n);
        }
    </script>

{% endblock %}

templates/vote/detail.html
{% extends 'base.html' %}
{% block con %}

{% load mathfilters %}
    <div class="container mt-5 mb-5">
        <h1><b>{{ t.subject }}</b></h1>
        
        
        <div class="row mt-5">
            <div class="col-lg-9">
                <textarea class="form-control" style="height:200px; font-size: 25px; font-weight: bold;" disabled>{{ t.content }}</textarea>
            </div>
            <div class="col-lg-3">
                <img src="{{ t.maker.getpic }}" width="100%">
                <div class="text-center mt-3">
                    <h4>created by <b>{{ t.maker }}</b></h4>
                </div>
            </div>
        </div>

        <hr>

        {% if user in t.voter.all %}
            
            <div class="row mt-5">
                {% for i in cset %}
                    <div class="col-lg-4 text-center">
                        <div class="progress mb-3">
                            <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: {{ i.choicer.count|div:t.voter.count|mul:100 }}%">{{ i.choicer.count|div:t.voter.count|mul:100|floatformat:2 }}%</div>
                        </div>
                        <img src="{{ i.pic.url }}" width="100%">
                        <h4 class="mt-3"><b>{{ i.name }}</b></h4>
                        <textarea class="form-control" style="font-size: 20px; font-weight: bold;" disabled>{{ i.con }}</textarea>
                    </div>
                {% endfor %}
            </div>
            <div class="text-end mt-4">
                <a class="btn btn-danger btn-lg" href="{% url 'vote:cancel' t.id %}">투표취소</a>
            </div>
    
        {% else %}
            <form method="post" action="{% url 'vote:vote' t.id %}">
                {% csrf_token %}
                <div class="row mt-5">
                    {% for i in cset %}
                        <div class="col-lg-4 text-center">
                            <input class="form-check-input mb-3" type="radio" {% if forloop.first %} checked {% endif %} name="cho" value="{{ i.id }}">
                            <img src="{{ i.pic.url }}" width="100%">
                            <h4 class="mt-3"><b>{{ i.name }}</b></h4>
                            <textarea class="form-control" style="font-size: 20px; font-weight: bold;" disabled>{{ i.con }}</textarea>
                        </div>
                    {% endfor %}
                </div>

                <div class="text-end mt-4">
                    <button class="btn btn-dark btn-lg">투표하기</button>
                </div>
            </form>
        {% endif %}

        


    </div>
{% endblock %}

templates/vote/index.html
{% extends 'base.html' %}
{% block con %}
    
    <div class="container mt-5 mb-5">
        <h1><b>투표소</b></h1>

        <div class="text-end">
            <a href="{% url 'vote:create' %}" class="btn btn-lg btn-dark">토픽생성</a>
        </div>


        <div class="row">
            {% for i in tset %}
                <div class="col-lg-4 mt-5">
                    <div class="card">
                        <img src="{{ i.maker.getpic }}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title"><b>{{ i.subject }}</b></h5>
                            <p class="card-text">{{ i.summary }}</p>
                            <div class="text-center">
                                {% if user in i.voter.all %}
                                    <a href="{% url 'vote:detail' i.id %}" class="btn btn-outline-dark btn-lg">결과보기</a>
                                {% else %}
                                    <a href="{% url 'vote:detail' i.id %}" class="btn btn-dark btn-lg">투표하기</a>
                                {% endif %}
                                {% if user == i.maker %}
                                    <button type="button" class="btn btn-outline-danger btn-lg" data-bs-toggle="modal" data-bs-target="#test{{forloop.counter}}">
                                        삭제하기
                                    </button>
                                {% endif %}


                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>



    </div>


    {% for i in tset %}
        {% if i.maker == user %}
            <div class="modal fade" id="test{{forloop.counter}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title" id="exampleModalLabel"><b>토픽 삭제 알림</b></h4>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <div class="mt-5 mb-5">
                                <h4><b>『{{ i.subject }}』</b> 는 {{ i.voter.count }} 명이 참여한 투표입니다. 그래도 삭제하시겠습니까?</h4>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">창닫기</button>
                            <a class="btn btn-danger" href="{% url 'vote:delete' i.id %}">삭제</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
    {% endfor %}




{% endblock %}