acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.userlogin, name="login"),
    path('signup/', views.signup, name="signup"),
    path('logout/', views.userlogout, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update")
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include("acc.urls")),
    path('board/', include("board.urls")),
    path('vote/', include("vote.urls")),
    path('trans/', include("trans.urls")),
    path('book/', include("book.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

acc/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class User(AbstractUser):
    pic = models.ImageField(upload_to="usr/%y")
    comment = models.TextField()
    point = models.IntegerField(default=0)

    # pip install pillow
    def getpic(self):
        if self.pic:
            return self.pic.url
        return "/media/noimage.png"

acc/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import check_password
from .models import User
# Create your views here.

def update(request):
    if request.method == "POST":
        u = request.user
        up = request.POST.get("upass")
        ue = request.POST.get("umail")
        uc = request.POST.get("ucomm")
        pi = request.FILES.get("upic")
        if up:
            u.set_password(up)
        u.email = ue
        u.comment = uc
        if pi:
            u.pic.delete()
            u.pic = pi
        u.save()
        login(request, u)
        return redirect("acc:profile")

    return render(request, "acc/update.html")


def delete(request):
    ck = request.POST.get("pwck")
    if check_password(ck, request.user.password):
        request.user.pic.delete()
        request.user.delete()
        return redirect("acc:index")
    else:
        pass # 메세지 19일
        return redirect("acc:profile") 

def profile(request):
    return render(request, "acc/profile.html")


def userlogout(request):
    logout(request)
    return redirect("acc:index")

def signup(request):
    if request.method == "POST":
        un = request.POST.get("uname")
        up = request.POST.get("upass")
        uc = request.POST.get("ucomm")
        pi = request.FILES.get("upic")
        try:
            User.objects.create_user(username=un, password=up, comment=uc, pic=pi)
            return redirect("acc:login")
        except:
            pass # 19일 메세지
    return render(request, "acc/signup.html")


def userlogin(request):
    if request.method == "POST":
        un = request.POST.get("uname")
        up = request.POST.get("upass")
        user = authenticate(username=un, password=up)
        if user:
            login(request, user)
            return redirect("acc:index")
        else:
            pass # 19일 메세지
    return render(request, "acc/login.html")


def index(request):
    return render(request, "acc/index.html")

templates/acc/index.html
{% extends 'base.html' %}

{% block con %}

    <div class="p-5 mb-4 bg-light rounded-3">
        <div class="container-fluid py-5">
            <h1 class="display-5 fw-bold">김치찌개 좋아하시는 분 ~~ </h1>
            <p class="col-md-8 fs-4">WELCOME 💎{{user}}💎</p>
            <a href=""><button class="btn btn-dark btn-lg" type="button" style="font-weight: bold;">CLICK</button></a>
        </div>
    </div>

{% endblock %}

templates/acc/login.html
{% extends 'base.html' %}
{% block con %}
    <div class="container mt-5 mb-5">
        <form method="post">
            {% csrf_token %}
            <h1><b>로그인</b></h1>

            <div class="mt-5">
                <input type="text" name="uname" class="form-control" placeholder="INPUT USERNAME" style="font-weight: bold;">
                <input type="password" name="upass" class="form-control mt-4" placeholder="INPUT PASSWORD" style="font-weight: bold;">
            </div>
            <div class="text-end mt-4">
                <button class="btn btn-dark">LOGIN</button>
            </div>
        </form>
    </div>

{% endblock %}

templates/acc/profile.html
{% extends 'base.html' %}
{% block con %}
    <div class="container mt-5 mb-5" style="font-size: 20px; font-weight: bold;">
        <h1><b>프로필</b></h1>
        <div class="text-center mt-5">
            <img src="{{ user.getpic }}" class="rounded-circle" height="250px">
        </div>
        <div class="mb-3 mt-5">
            <label class="form-label">USERNAME</label>
            <input type="text" value="{{user}}" disabled class="form-control" style="font-weight: bold;">
        </div>
        <div class="mb-3">
            <label class="form-label">POINT</label>
            <input type="text" value="{{user.point}} P" style="font-weight: bold;" disabled class="form-control">
        </div>
        <div class="mb-3">
            <label class="form-label">EMAIL</label>
            <input type="text" value="{{ user.email }}" style="font-weight: bold;" disabled class="form-control">
        </div>
        <div class="mb-3">
            <label class="form-label">COMMENT</label>
            <textarea class="form-control" disabled style="font-weight: bold; height: 100px;">{{ user.comment }}</textarea>
        </div>

        <div class="text-end">
            <a href="{% url 'acc:update' %}" class="btn btn-dark">정보수정</a>
            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
                계정삭제
            </button>
        </div>
    </div>



    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"><b>계정삭제 알림창</b></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" action="{% url 'acc:delete' %}">
                    {% csrf_token %}
                    <div class="modal-body text-center">
                        <h4>패스워드를 입력해주세요</h4>
                        <input type="password" name="pwck" class="form-control mt-3 mb-2">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                        <button class="btn btn-danger">삭제</button>
                    </div>
                </form>
            </div>
        </div>
    </div>



{% endblock %}

templates/acc/signup.html
{% extends 'base.html' %}
{% block con %}
    <div class="container mt-5 mb-5" style="font-weight: bold; font-size: 20px;">
        <h1><b>회원가입</b></h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3 mt-5">
                <label class="form-label">USERNAME</label>
                <input name="uname" type="text" class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">PASSWORD</label>
                <input name="upass" type="password" class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">COMMENT</label>
                <textarea name="ucomm" class="form-control"></textarea>
            </div>
            <div class="mb-3">
                <label class="form-label">USERPIC</label>
                <input type="file" name="upic" class="form-control">
            </div>
            <div class="mt-4 text-end">
                <button class="btn btn-dark" style="font-weight: bold;">회원가입</button> 
            </div>
        </form>
    </div>
{% endblock %}

templates/acc/update.html
{% extends 'base.html' %}
{% block con %}
    <div class="container mt-5 mb-5"  style="font-size: 20px; font-weight: bold;">

        <h1><b>정보수정</b></h1>

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3 mt-5">
                <label class="form-label">USERNAME</label>
                <input type="text" value="{{user}}" disabled class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">PASSWORD</label>
                <input type="password" name="upass" class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">EMAIL</label>
                <input type="text" name="umail" value="{{ user.email }}" class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">COMMENT</label>
                <textarea class="form-control" name="ucomm">{{ user.comment }}</textarea>
            </div>
            <div class="mb-3">
                <label class="form-label">USERPIC</label>
                <input type="file" name="upic" class="form-control">
            </div>
            <div class="text-end">
                <a href="{% url 'acc:profile' %}" class="btn btn-dark">BACK</a>
                <button class="btn btn-dark">UPDATE</button>
            </div>
        </form>
    </div>
{% endblock %}