acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.userlogin, name="login"),
    path('signup/', views.signup, name="signup"),
    path('logout/', views.userlogout, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update")
]

board/urls.py
from django.urls import path
from . import views

app_name = "board"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('detail/<bpk>', views.detail, name="detail"),
    path('delete/<bpk>', views.delete, name="delete"),
    path('create/', views.create, name="create"),
    path('update/<bpk>', views.update, name="update"),
    path('creply/<bpk>', views.creply, name="creply"),
    path('dreply/<bpk>/<rpk>', views.dreply, name="dreply"),
    path('likey/<bpk>', views.likey, name="likey"),
    path('unlikey/<bpk>', views.unlikey, name="unlikey")
]

book/urls.py
from django.urls import path
from . import views

app_name = "book"
urlpatterns =[
    path('index/', views.index, name="index"),
    path('create/', views.create, name="create")
 ]

conf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include("acc.urls")),
    path('board/', include("board.urls")),
    path('vote/', include("vote.urls")),
    path('trans/', include("trans.urls")),
    path('book/', include("book.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from django.db import models
from acc.models import User

# Create your models here.
class Board(models.Model):
    subject = models.CharField(max_length=100)
    writer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="writer")
    content = models.TextField()
    pubdate = models.DateTimeField()
    likey = models.ManyToManyField(User, blank=True, related_name="likey")

    def __str__(self):
        return self.subject

    def summary(self):
        if len(self.content) > 30:
            return f"{self.content[:30]} ..."
        return self.content

    def hot(self):
        if self.likey.count() > 1:
            return True
        return False
    

class Reply(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    replyer = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()
    pubdate = models.DateTimeField()

    def __str__(self):
        return f"{self.board}_{self.replyer}"

board/views.py
from django.shortcuts import render, redirect
from .models import Board, Reply
from django.utils import timezone
from django.core.paginator import Paginator

def likey(request, bpk):
    b = Board.objects.get(id=bpk)
    b.likey.add(request.user)
    return redirect("board:detail", bpk)
def unlikey(request, bpk):
    b = Board.objects.get(id=bpk)
    b.likey.remove(request.user)
    return redirect("board:detail", bpk)


def dreply(request, bpk, rpk):
    r = Reply.objects.get(id=rpk)
    if r.replyer == request.user:
        r.delete()
    else:
        pass # 19일차
    return redirect("board:detail", bpk)

def creply(request, bpk):
    b = Board.objects.get(id=bpk)
    c = request.POST.get("com")
    p = timezone.now()
    Reply(board=b, replyer=request.user, comment=c, pubdate=p).save()
    return redirect("board:detail", bpk)

def index(request):
    cate = request.GET.get("cate", "")
    kw = request.GET.get("kw", "")
    pg = request.GET.get("page", 1)

    if kw:
        if cate == "sub":
            b = Board.objects.filter(subject__startswith=kw)
        elif cate == "wri":
            try:
                from acc.models import User
                u = User.objects.get(username=kw)
                b = Board.objects.filter(writer=u)
            except:
                b = Board.objects.none()
        elif cate == "con":
            b = Board.objects.filter(content__contains=kw)
        else:
            # 19 일차
            b = Board.objects.all()
    else:
        b = Board.objects.all()

    pag = Paginator(b, 5)
    obj = pag.get_page(pg)
    context = {
        "bset" : obj,
        "kw" : kw,
        "cate" : cate
    }
    return render(request, "board/index.html", context)





def update(request, bpk):
    b = Board.objects.get(id=bpk)

    if b.writer != request.user:
        # 19일차 메세지~
        return redirect("board:index")

    if request.method == "POST":
        s = request.POST.get("sub")
        c = request.POST.get("con") 
        b.subject = s
        b.content = c
        b.save()
        return redirect("board:detail", bpk)

    context = {
        "b" : b
    }
    return render(request, "board/update.html", context)

def create(request):
    if request.method == "POST":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        Board(subject=s, content=c, writer=request.user, pubdate=timezone.now() ).save()
        return redirect("board:index")
    return render(request, "board/create.html")


def delete(request, bpk):
    b = Board.objects.get(id=bpk)
    if request.user == b.writer:
        b.delete()
    else:
        pass # 19 일 차
    return redirect("board:index")

def detail(request, bpk):
    b = Board.objects.get(id=bpk)
    r = b.reply_set.all()
    r = r.order_by("-pubdate")
    context = {
        "b": b,
        "rset" : r,
    }
    return render(request, "board/detail.html", context)

templates/board/create.html
{% extends 'base.html' %}
{% block con %}
    <div class="container mt-5 mb-5" style="font-size: 20px; font-weight: bold;">
        <h1><b>게시글 작성</b></h1>
        
        <form method="post">
            {% csrf_token %}
            <div class="mb-3 mt-5">
                <label class="form-label">SUBJECT</label>
                <input name="sub" type="text" class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">WRITER</label>
                <input type="text" class="form-control" value="{{ user }}" disabled>
            </div>
            <div class="mb-3">
                <label class="form-label">CONTENT</label>
                <textarea name="con" class="form-control" style="height: 150px;"></textarea>
            </div>
            <div class="text-end mt-3">
                <button class="btn btn-dark">생성</button>
            </div>
        </form>
        
    </div>
{% endblock %}

templates/board/detail.html
{% extends 'base.html' %}
{% block con %}
    <div class="container mt-5 mb-5">
        <h1><b>{{ b.subject }}</b></h1>

        <div class="row mt-5">
            <div class="col-lg-9">
                <textarea class="form-control" disabled style="height: 250px;">{{ b.content }}</textarea>
            </div>
            <div class="col-lg-3">
                <img src="{{ b.writer.getpic }}" width="100%">
                <div class="text-center mt-3">
                    <h5>written by <b>{{ b.writer }}</b></h5>
                </div>
                <div class="text-end mt-3">
                    {{ b.pubdate|date:'Y년 n월 j일 H:i' }}
                </div>
            </div>
        </div>

        <div class="text-end mt-4">
            <a href="{% url 'board:index' %}" class="btn btn-dark">글목록</a>
            {% if user == b.writer %}
                <a href="{% url 'board:update' b.id %}" class="btn btn-secondary">글수정</a>
                <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    글삭제
                </button>
            {% endif %}
        </div>

        <div class="text-end mt-4">
            {% if user in b.likey.all %}
                <a href="{% url 'board:unlikey' b.id %}" class="btn btn-danger btn-sm">👎🏻</a>
            {% else %}
                <a href="{% url 'board:likey' b.id %}" class="btn btn-primary btn-sm">👍🏻</a>
            {% endif %}
            
            <button type="button" class="btn btn-warning btn-sm" data-bs-toggle="modal" data-bs-target="#star">
                🍺
            </button>
        </div>


        <hr>

        <form method="post" action="{% url 'board:creply' b.id %}">
            {% csrf_token %}
            <div class="row mt-4 mb-5">
                <div class="col-lg-10">
                    <input type="text" name="com" class="form-control">
                </div>
                <div class="col-lg-2">
                    <button class="btn btn-dark" style="width: 100%;">댓글작성</button>
                </div>
            </div>
        </form>

        {% if rset %}
            {% for i in rset %}
                <div class="row mt-5">
                    <div class="col-lg-3">
                        <img src="{{ i.replyer.getpic }}" width="100%">
                        <div class="text-center mt-3">
                            <h5><b>{{ i.replyer }}</b></h5>
                        </div>
                    </div>
                    <div class="col-lg-9">
                        <textarea class="form-control" style="height: 150px; font-size: 25px; font-weight: bold;" disabled>{{ i.comment }}</textarea>
                        <div class="text-end mt-3">
                            {% if i.replyer == user %}
                                <a href="{% url 'board:dreply' b.id i.id %}" class="btn btn-danger">댓글삭제</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
        {% endif %}



    
    </div>


    <form method="post" action="{% url 'book:create' %}">
        {% csrf_token %}
        <div class="modal fade" id="star" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">북마크 추가 알림창</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body text-center">
                        <div class="text-end mb-4">
                            <input name="impo" type="checkbox" class="btn-check" id="btn-check-outlined" autocomplete="off">
                            <label class="btn btn-outline-warning" for="btn-check-outlined">✨</label><br>
                        </div>
                        <textarea class="form-control" name="scon" placeholder="사이트를 간략하게 설명해주세요" style="height: 100px;"></textarea>
                        <input type="hidden" name="surl" value="{{ request.path }}">
                        <input type="hidden" name="sname" value="[게시판]{{ b.subject }}">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                        <button class="btn btn-warning">추가</button>
                    </div>
                </div>
            </div>
        </div>
    </form>









    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">게시글 삭제 알림</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <h4>진짜 '<b>[게시글]{{b.subject}}</b>'  를 삭제하시겠습니까?</h4>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">취소</button>
                    <a href="{% url 'board:delete' b.id %}" class="btn btn-danger">삭제</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/board/index.html
{% extends 'base.html' %}
{% block con %}

    {% load mathfilters %}

    <div class="container mt-5 mb-5">

        <h1><b>게시판</b></h1>

        <div class="text-end">
            <a class="btn btn-dark" href="{% url 'board:create' %}">CREATE</a>
        </div>

        <table class="table table-hover mt-5">
            <thead style="background-color: black; color:white;" class="text-center">
                <tr>
                    <th scope="col">NO</th>
                    <th scope="col">SUBJECT</th>
                    <th scope="col">SUMMARY</th>
                    <th scope="col">WRITER</th>
                    <th scope="col">LIKEY</th>
                </tr>
            </thead>
            <tbody>
                {% if bset %}
                    {% for i in bset %}
                        <tr>
                            <th scope="row">{{ bset.start_index|add:forloop.counter0 }}</th>
                            <td><a class="sub" href="{% url 'board:detail' i.id %}">{% if i.hot %}❣{% endif %}{{ i.subject }}</a></td>
                            <td>{{ i.summary }}</td>
                            <td>{{ i.writer }}</td>
                            <td>{{ i.likey.count }}</td>
                        </tr>
                    {% endfor %}
                {% else %}
                    {% if kw %}
                        <tr>
                            <th colspan="5"><h4 class="text-center"><b>검색결과가 없습니다 😒</b></h4></th>
                        </tr>
                    {% else %}
                        <tr>
                            <th colspan="5"><h4 class="text-center"><b>첫번째 게시글을 등록해주세요 👏</b></h4></th>
                        </tr>
                    {% endif %}
                {% endif %}
            </tbody>
        </table>


        <nav aria-label="Page navigation example" class="mt-4">
            <ul class="pagination justify-content-center">

                {% if bset.has_previous %}
                    <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page=1&cate={{cate}}&kw={{kw}}" tabindex="-1">처음</a></li>
                    <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{ bset.previous_page_number }}&cate={{cate}}&kw={{kw}}" tabindex="-1">이전</a></li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link" tabindex="-1">처음</a></li>
                    <li class="page-item disabled"><a class="page-link" tabindex="-1">이전</a></li>
                {% endif %}
                

                {% for i in bset.paginator.page_range %}
                    {% if i >= bset.number|sub:3 and bset.number|add:3 >= i %}
                        <li class="page-item {% if i == bset.number %} active {% endif %}"><a class="page-link" href="{% url 'board:index' %}?page={{i}}&cate={{cate}}&kw={{kw}}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}


                {% if bset.has_next %}
                    <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{ bset.next_page_number }}&cate={{cate}}&kw={{kw}}" tabindex="-1">다음</a></li>
                    <li class="page-item"><a class="page-link" href="{% url 'board:index' %}?page={{ bset.paginator.num_pages }}&cate={{cate}}&kw={{kw}}" tabindex="-1">마지막</a></li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link" tabindex="-1">다음</a></li>
                    <li class="page-item disabled"><a class="page-link" tabindex="-1">마지막</a></li>
                {% endif %}
                


            </ul>
        </nav>

        <form>
            <div class="row mt-4"> 
                <div class="col-lg-2">
                    <select class="form-select mb-3" name="cate" aria-label=".form-select-lg example">
                        <option value="sub" {% if cate == 'sub' %} selected {% endif %}>제목</option>
                        <option value="wri" {% if cate == 'wri' %} selected {% endif %}>작성자</option>
                        <option value="con" {% if cate == 'con' %} selected {% endif %}>내용</option>
                    </select>
                </div>
                <div class="col-lg-8">
                    <input type="text" name="kw" value="{{kw}}" class="form-control">
                </div>
                <div class="col-lg-2 text-center">
                    <button class="btn btn-dark">검색</button>
                    <a href="{% url 'board:index' %}" class="btn btn-dark">리셋</a>
                </div>
            </div>
        </form>

    </div>

    <style>
        .sub{
            text-decoration: none;
            font-size: 20px;
            font-weight: bold;
            color:black;
        }
        .sub:hover{
            color:red;
        }
    </style>
{% endblock %}

templates/board/update.html
{% extends 'base.html' %}
{% block con %}
    <div class="container mt-5 mb-5" style="font-size: 20px; font-weight: bold;">
            
        <h1><b>게시글수정</b></h1>

        <form method="post">
            {% csrf_token %}
            <div class="mb-3 mt-5">
                <label class="form-label">SUBJECT</label>
                <input type="text" name="sub" value="{{b.subject}}" class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">WRITER</label>
                <input type="text" class="form-control" disabled value="{{ b.writer }}">
            </div>
            <div class="mb-3">
                <label class="form-label">CONTENT</label>
                <textarea class="form-control" name="con" style="height: 150px;">{{ b.content }}</textarea>
            </div>
            <div class="text-end mt-3">
                <button class="btn btn-dark">수정</button>
            </div> 
        </form>
    </div>
{% endblock %}